export const PATHS = {
  HOME: '/',
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    RECOVER_PASSWORD: '/recover-password',
  },
  DASHBOARD: '/dashboard',
  SHOP: '/shop',
  SHOPS: '/dashboard/shops',
  CATALOG: '/dashboard/catalog',
  FINANCES: '/dashboard/finances',
  CUSTOMERS: '/dashboard/customers',
  MARKETING: '/dashboard/marketing',
  ANALYTICS: '/dashboard/analytics',
  INTEGRATIONS: '/dashboard/integrations',
  CATEGORIES: '/dashboard/categories',
  ORDERS: '/dashboard/orders',
  BRANCHES: '/dashboard/branches',
  STAFF: '/dashboard/staff',
  INVENTORY: '/dashboard/inventory',
  BRANCH_DETAIL: '/branch/:id',
  CART: '/cart',
  CHECKOUT: '/checkout',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/product/:slug',
  PROFILE: '/profile',
  WALLET: '/profile/wallet',
  MY_ORDERS: '/profile/orders',
  ORDER_DETAIL: '/profile/orders/:id',
  VNPAY_RESULT: '/order/vnpay-result',
  NOT_FOUND: '*',
} as const;
